name: pipeline
on: 
  push:
    branches:
      - main
      - master

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: code
        run: echo " CODE "

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo " BUILD "

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo " TEST "

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo " DEPLOY "
