name: pipeline

#PIPELINE
on: 
  workflow_dispatch: 

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: code
        run: echo " CODE "

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo " BUILD "

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo " TEST "

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo " DEPLOY "
