name: git-action 
on: workflow_dispatch
#
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    - name: fetch code
      run: echo "code fetched"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
    - name: building container
      run: echo "Building Container for Code"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Testing Code
      run: echo " Testing Code on Container"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: deploy site
      run: echo " Deploying on UAT"
